### PR TITLE
Accept text as env var as well

### PR DESCRIPTION
**Pull request by maathor**

### CODE REVIEW

**Comment by cawoodm** [comment]
Would be great if `-text` was just optional with some simple default (like "hello").

This would make simple demos with `kubectl create deploy echo hashicorp/http-echo` work out of the box. As it is you can't pass args this way.

**Comment by displague** [comment]
https://github.com/hashicorp/http-echo/pull/6 appears to be a more recent dupe with mildly cleaner implementation.

> Would be great if -text was just optional with some simple default (like "hello").

I agree. That could happen in another PR.

**Review by baskoopmans — APPROVED** [review]

**Comment by 1oglop1** [comment]
@david-yu Any plans on looking at this or better merging it?

**Comment by DanStough** [comment]
Just an FYI that this PR was closed automatically because we moved the default branch from `master` to `main`. We're revisiting these PRs before an upcoming release of this project. Feel free to re-submit against `main` if you get to it before us.

**Comment by DanStough** [comment]
After reviewing this PR and #6, I will re-open #6 and merge that. Much appreciate the discussion here 🙏 !

I noticed this PR has `ENV` in the Dockerfile, but as I understand, this doesn't need to be declared to set at runtime.

**Pull request closed without merging**
