### PR TITLE
Use non root user

### PR DESCRIPTION
**Pull request by DanStough**
re-opening #9 from @kschoche

### CODE REVIEW

**Comment by kschoche** [comment]
Ah, you got to this before me.. I'll delete my 2nd PR and we can keep this one!
Thanks!

**Comment by DanStough** [comment]
@kschoche made similar changes to the `scratch` image, which I believe is the default on docker hub. Also switched from `100` to `1005` because ubuntu complained.

**Comment by DanStough** [comment]
Article I used for scratch image as reference: https://medium.com/@lizrice/non-privileged-containers-based-on-the-scratch-image-a80105d6d341

**Comment by kschoche** [comment]
@DanStough Cool, that is a good idea to get the scratch image in the same state! I haven't tested it but just wanted to confirm that it doesn't break things (maybe run the consul-k8s acceptance tests against this image?)

**Review by kschoche — APPROVED** [review]
Thanks!!

**Comment by DanStough** [comment]
Ran against some basic connect service tests. LGTM!

**Pull request merged**
